version: "2"
services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        volumes:
            - ./docker/mysql:/var/lib/mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
networks:
    default:
        driver: bridge
